# -*- coding: utf-8 -*-
"""vending-machine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1At0SFm3U4F4ZwSvHi-YKBcoYrYks3XhZ
"""

# define the items and their prices
items = {'coke': 1.50, 'pepsi': 1.25, 'water': 1.00}

# define a function to display the menu
def show_menu():
    print("Welcome to the vending machine!")
    print("Here's what we have:")
    for item, price in items.items():
        print(f"{item}: ${price:.2f}")

# define a function to get the user's selection
def get_selection():
    while True:
        selection = input("Enter the name of the item you want: ")
        if selection in items:
            return selection
        else:
            print("Sorry, that item is not available.")

# define a function to dispense the selected item
def dispense_item(selection):
    price = items[selection]
    print(f"Please insert ${price:.2f} to get your {selection}.")
    while True:
        amount = float(input("Insert money: "))
        if amount >= price:
            change = amount - price
            print(f"Here's your {selection}.")
            if change > 0:
                print(f"Don't forget your change: ${change:.2f}")
            break
        else:
            print("Please insert more money.")

# main function to run the simulation
def run_vending_machine():
    show_menu()
    selection = get_selection()
    dispense_item(selection)

# run the simulation
run_vending_machine()